/** Quiet Intelligence Console authentication: generous calm space, unambiguous steps, and no fabricated account actions. */

import { BrandLockup } from "@/components/BrandMark";
import { useAuth } from "@/contexts/AuthContext";
import { ThemeToggle } from "@/components/ThemeToggle";
import { api, ApiUnavailableError } from "@/services/api";
import { ArrowLeft, ArrowRight, CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

type AuthMode = "login" | "register" | "google" | "verify" | "forgot";

function showBackendRequired() {
  toast.error("Backend connection required", { description: "This interface is ready for the FastAPI auth service; no account action was simulated." });
}

function AuthShell({ children, label }: { children: React.ReactNode; label: string }) {
  return (
    <div className="grid min-h-screen bg-background lg:grid-cols-[0.9fr_1.1fr]">
      <div className="relative hidden overflow-hidden bg-[color:var(--ink-soft)] p-10 text-white lg:flex lg:flex-col">
        <Link href="/"><BrandLockup className="[&>span]:text-white" /></Link>
        <div className="relative z-10 my-auto max-w-[430px]"><p className="index-label text-white/55">{label}</p><h1 className="font-display mt-5 text-[52px] font-semibold leading-[0.98] tracking-[-0.06em]">A private memory layer for every model you choose.</h1><p className="mt-6 leading-7 text-white/65">Build a clear record of what matters, then carry that context between connected AI providers and local models.</p><div className="mt-10 space-y-4">{['Memory stays separate from conversation history', 'Model selection remains explicit', 'Data controls stay visible'].map((line) => <p key={line} className="flex items-center gap-3 text-sm text-white/75"><CheckCircle2 className="h-4 w-4 text-[color:var(--memory-teal-light)]" />{line}</p>)}</div></div>
        <div className="relative z-10 text-xs text-white/45">AI Memory Hub · User-controlled context</div><div className="absolute -bottom-16 -right-16 h-[360px] w-[360px] rounded-full border-[60px] border-white/[0.06]" /><div className="absolute left-0 top-[27%] h-px w-full bg-gradient-to-r from-transparent via-[color:var(--memory-teal)]/60 to-transparent" />
      </div>
      <div className="relative flex min-h-screen items-center justify-center px-5 py-10 sm:px-8"><div className="absolute right-6 top-5 flex items-center gap-3"><Link href="/" className="hidden text-xs font-bold text-muted-foreground hover:text-foreground sm:inline">Back to site</Link><ThemeToggle /></div><div className="w-full max-w-[430px]">{children}</div></div>
    </div>
  );
}

function AuthTitle({ title, subtitle }: { title: string; subtitle: string }) { return <><p className="index-label text-[color:var(--memory-teal-deep)] dark:text-[color:var(--memory-teal-light)]">Secure access</p><h2 className="font-display mt-3 text-[34px] font-semibold tracking-[-0.055em]">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{subtitle}</p></>; }
function Field({ label, type = "text", placeholder, icon, right, value, onChange }: { label: string; type?: string; placeholder: string; icon?: React.ReactNode; right?: React.ReactNode; value?: string; onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void }) { return <label className="block"><span className="mb-2 block text-xs font-bold text-foreground">{label}</span><span className="relative block">{icon && <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">{icon}</span>}<input type={type} placeholder={placeholder} value={value} onChange={onChange} className={`h-11 w-full rounded-xl border border-input bg-card text-sm outline-none transition placeholder:text-muted-foreground/75 focus:border-[color:var(--memory-teal)] focus:ring-4 focus:ring-[color:color-mix(in_oklab,var(--memory-teal)_13%,transparent)] ${icon ? 'pl-10' : 'px-3.5'} ${right ? 'pr-11' : 'pr-3.5'}`} />{right}</span></label>; }
function SolidButton({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <button onClick={onClick} type="button" className="inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[color:var(--memory-teal)] px-4 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[color:var(--memory-teal-deep)] active:scale-[0.97]">{children}</button>; }
function GoogleButton({ onClick }: { onClick: () => void }) { return <button onClick={onClick} type="button" className="inline-flex h-12 w-full items-center justify-center gap-3 rounded-xl border border-border bg-card text-sm font-bold transition hover:bg-secondary active:scale-[0.97]"><span className="font-display text-lg font-bold text-[#4285F4]">G</span> Continue with Google</button>; }

export default function AuthPage({ mode }: { mode: AuthMode }) {
  const [, navigate] = useLocation();
  const { signIn, verifyEmail } = useAuth();
  const [passwordVisible, setPasswordVisible] = useState(false);
  const [notice, setNotice] = useState(false);
  const [email, setEmail] = useState(() => sessionStorage.getItem("ai-memory-hub.pending-email") ?? "");
  const [password, setPassword] = useState("");
  const [fullName, setFullName] = useState("");
  const [otp, setOtp] = useState("");
  const submit = () => { setNotice(true); };
  const showError = (error: unknown) => toast.error(error instanceof Error ? error.message : "Request failed");

  if (mode === "verify") return <AuthShell label="Email verification"><div><Link href="/register" className="inline-flex items-center gap-2 text-xs font-bold text-muted-foreground transition hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5" /> Back to registration</Link><div className="mt-9"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[color:color-mix(in_oklab,var(--memory-teal)_13%,transparent)]"><Mail className="h-5 w-5 text-[color:var(--memory-teal)]" /></span><div className="mt-6"><AuthTitle title="Confirm your email" subtitle="Enter the six-digit code sent to your inbox. This first-time verification protects your workspace." /></div><div className="mt-8"><Field label="Email address" type="email" placeholder="you@example.com" icon={<Mail className="h-4 w-4" />} value={email} onChange={(event) => setEmail(event.target.value)} /><Field label="Verification code" placeholder="123456" value={otp} onChange={(event) => setOtp(event.target.value.replace(/\D/g, "").slice(0, 6))} /></div><div className="mt-5"><SolidButton onClick={() => { verifyEmail(email, otp).then(() => { sessionStorage.removeItem("ai-memory-hub.pending-email"); navigate("/chat"); }).catch(showError); }}><ShieldCheck className="h-4 w-4" /> Verify email</SolidButton></div></div></div></AuthShell>;

  if (mode === "google") return <AuthShell label="Google sign in"><div><Link href="/login" className="inline-flex items-center gap-2 text-xs font-bold text-muted-foreground transition hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5" /> Other sign-in options</Link><div className="mt-9 rounded-2xl border border-border bg-card p-6 sm:p-8"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#4285F4]/10 font-display text-2xl font-bold text-[#4285F4]">G</div><h2 className="font-display mt-6 text-[30px] font-semibold tracking-[-0.05em]">Continue with Google</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Your Google account handles sign-in. AI Memory Hub will request only the access needed to identify your account.</p><GoogleButton onClick={() => { api.auth.beginGoogleOAuth().then(({ authorization_url }) => { window.location.assign(authorization_url); }).catch(showError); }} /><p className="mt-5 text-center text-[11px] leading-5 text-muted-foreground">By continuing, you will be redirected to your configured authentication service.</p></div></div></AuthShell>;

  if ((mode as AuthMode) === "verify") return null;

  if (mode === "forgot") return <AuthShell label="Account recovery"><div><Link href="/login" className="inline-flex items-center gap-2 text-xs font-bold text-muted-foreground transition hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5" /> Back to sign in</Link><div className="mt-9"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[color:color-mix(in_oklab,var(--memory-teal)_13%,transparent)]"><LockKeyhole className="h-5 w-5 text-[color:var(--memory-teal)]" /></span><div className="mt-6"><AuthTitle title="Reset your password" subtitle="We’ll send a password reset link to the verified email on your account." /></div><div className="mt-8 space-y-5"><Field label="Email address" type="email" placeholder="you@example.com" icon={<Mail className="h-4 w-4" />} value={email} onChange={(event) => setEmail(event.target.value)} /><SolidButton onClick={() => { api.auth.requestPasswordReset(email).then(() => setNotice(true)).catch(showError); }}>Send reset link <ArrowRight className="h-4 w-4" /></SolidButton>{notice && <p className="rounded-xl border border-[color:color-mix(in_oklab,var(--memory-teal)_28%,transparent)] bg-[color:color-mix(in_oklab,var(--memory-teal)_7%,transparent)] p-3 text-xs leading-5 text-[color:var(--memory-teal-deep)] dark:text-[color:var(--memory-teal-light)]">A password reset code will be sent if the account exists.</p>}</div></div></div></AuthShell>;

  const isRegister = mode === "register";
  return <AuthShell label={isRegister ? "Create your workspace" : "Welcome back"}><div className="lg:hidden"><Link href="/"><BrandLockup /></Link></div><div className="mt-9 lg:mt-0"><AuthTitle title={isRegister ? "Create your private hub" : "Sign in to your workspace"} subtitle={isRegister ? "Start with a verified account, then connect only the AI providers you choose." : "Continue with your user-controlled AI memory workspace."} /><div className="mt-8 space-y-5">{isRegister && <Field label="Full name" placeholder="Alex Morgan" value={fullName} onChange={(event) => setFullName(event.target.value)} />}{isRegister && <Field label="Email address" type="email" placeholder="you@example.com" icon={<Mail className="h-4 w-4" />} value={email} onChange={(event) => setEmail(event.target.value)} />}{!isRegister && <Field label="Email address" type="email" placeholder="you@example.com" icon={<Mail className="h-4 w-4" />} value={email} onChange={(event) => setEmail(event.target.value)} />}<Field label="Password" type={passwordVisible ? "text" : "password"} placeholder="••••••••••••" icon={<LockKeyhole className="h-4 w-4" />} value={password} onChange={(event) => setPassword(event.target.value)} right={<button type="button" onClick={() => setPasswordVisible((value) => !value)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground" aria-label={passwordVisible ? 'Hide password' : 'Show password'}>{passwordVisible ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button>} />{!isRegister && <div className="flex justify-end"><Link href="/forgot-password" className="text-xs font-bold text-[color:var(--memory-teal-deep)] dark:text-[color:var(--memory-teal-light)]">Forgot password?</Link></div>}<SolidButton onClick={() => { if (isRegister) { api.auth.register(email, password, fullName).then(() => { sessionStorage.setItem("ai-memory-hub.pending-email", email); navigate("/verify-email"); }).catch(showError); } else { signIn(email, password).then(() => navigate("/chat")).catch(showError); } }}>{isRegister ? 'Create account' : 'Sign in'} <ArrowRight className="h-4 w-4" /></SolidButton></div><div className="my-6 flex items-center gap-3 text-[11px] text-muted-foreground before:h-px before:flex-1 before:bg-border after:h-px after:flex-1 after:bg-border">or</div><GoogleButton onClick={() => navigate("/auth/google")} /><p className="mt-7 text-center text-xs text-muted-foreground">{isRegister ? <>Already have an account? <Link href="/login" className="font-bold text-[color:var(--memory-teal-deep)] dark:text-[color:var(--memory-teal-light)]">Sign in</Link></> : <>New to AI Memory Hub? <Link href="/register" className="font-bold text-[color:var(--memory-teal-deep)] dark:text-[color:var(--memory-teal-light)]">Create account</Link></>}</p></div></AuthShell>;
}
